declare module '@types/boxicons' {
  export type BoxIconName =
    | 'back'
    | 'menu'
    | 'close'
    | 'search'
    | 'filter'
    | 'sort'
    | 'add'
    | 'edit'
    | 'delete'
    | 'save'
    | 'success'
    | 'error'
    | 'warning'
    | 'info'
    | 'notification'
    | 'user'
    | 'userCircle'
    | 'settings'
    | 'logout'
    | 'home'
    | 'calendar'
    | 'location'
    | 'phone'
    | 'email'
    | 'message'
    | 'image'
    | 'camera'
    | 'upload'
    | 'download'
    | 'star'
    | 'heart'
    | 'bookmark'
    | 'link'
    | 'share'
    | 'more';
} 